const ACTION_TYPE = {
    SET_DATA : "SET_DATA",
    ERROR:"ERROR",
    FETCH_DATA: "FETCH_DATA",
    SET_FILTERS: "SET_FILTERS", 
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    LOGOUT : "LOGOUT",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
    CLEAR_WISHLIST: "CLEAR_WISHLIST",
    GET_WISHLIST:"GET_WISHLIST",
}

export default ACTION_TYPE;